version: "3.7"

services:
  extralogic-data:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_NAME: extralogicdata
      DB_USER: extralogicdata
      DB_PASSWORD: extralogicdata
      FLASK_APP: src
    ports:
      - 5000:5000
    restart: on-failure:10

#  postgres_db:
#    image: postgres:14.2
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_DB: extralogicdata
#      POSTGRES_USER: extralogicdata
#      POSTGRES_PASSWORD: extralogicdata
